"""initial schema

Revision ID: 0fc5a646d20c
Revises: 
Create Date: 2026-06-03 19:47:30.587946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fc5a646d20c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('OPENWEBUI', 'OLLAMA', 'GEMINI', name='ai_provider_enum'), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('input_type', sa.Enum('NAME', 'URL', 'REPO', name='input_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMING', 'RUNNING', 'COMPLETE', 'FAILED', name='assessment_status_enum'), nullable=False),
    sa.Column('review_mode', sa.Enum('STANDARD', 'DEEP_REVIEW', name='review_mode_enum'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('overall_rag', sa.Enum('RED', 'AMBER', 'GREEN', name='rag_status_enum'), nullable=True),
    sa.Column('recommendation', sa.Enum('APPROVE', 'CONDITIONAL', 'REJECT', name='recommendation_enum'), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('VENDOR_TRUST', 'CVE', 'MAINTENANCE', 'DEPENDENCY', 'ENCRYPTION', 'LOGGING', 'DATA_EXFILTRATION', 'THIRD_PARTY', name='category_enum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rag', sa.Enum('RED', 'AMBER', 'GREEN', name='rag_status_enum'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('ai_suggested_name', sa.String(), nullable=False),
    sa.Column('ai_suggested_vendor', sa.String(), nullable=False),
    sa.Column('ai_suggested_url', sa.String(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_confirmations')
    op.drop_table('assessment_findings')
    op.drop_table('audit_log')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ai_provider_config')
    # ### end Alembic commands ###
