"""add executive_summary to assessments

Revision ID: 4ad1d1ddff9b
Revises: 89b6e24a560c
Create Date: 2026-06-04 13:17:19.635428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad1d1ddff9b'
down_revision: Union[str, None] = '89b6e24a560c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('executive_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'executive_summary')
    # ### end Alembic commands ###
