"""add project_scope to assessments

Revision ID: 89b6e24a560c
Revises: 0fc5a646d20c
Create Date: 2026-06-04 12:56:52.264682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b6e24a560c'
down_revision: Union[str, None] = '0fc5a646d20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('project_scope', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'project_scope')
    # ### end Alembic commands ###
